FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y procps && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY app.py .
COPY start-without-exec.sh .

RUN chmod +x start-without-*.sh
RUN pip3 install flask

# 👉 Swap the CMD below to test each version

# ✅ Graceful version
# CMD ["./start-with-exec.sh"]

# ❌ Non-graceful version
CMD ["./start-without-exec.sh"]
