FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y procps && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY app.py .
COPY start-with-exec.sh .

RUN chmod +x start-with-*.sh
RUN pip3 install flask


# ✅ Graceful version
CMD ["./start-with-exec.sh"]


